const data = {
  products: [
    {
      // _id: "1",
      name: "nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirt",
      image: "/images/p1.png",
      price: 120,
      countInStock:2,
      brand: "Nike",
      rating: 4.5,
      numReviews: 89,
      description: "high quality shirt",
    },
    {
      // _id: "2",
      name: "adidas slim shirt",
      slug: "adidas-slim-shirt",
      category: "Shirt",
      image: "/images/p2.png",
      price: 100,
      countInStock: 0,
      brand: "adidas",
      rating: 3.5,
      numReviews: 9,
      description: "high quality shirt",
    },
    {
      // _id: "3",
      name: "puma slim shirt",
      slug: "puma-slim-shirt",
      category: "Shirt",
      image: "/images/p3.png",
      price: 188,
      countInStock: 15,
      brand: "puma",
      rating: 5.5,
      numReviews: 12,
      description: "high quality shirt",
    },
    {
      // _id: "4",
      name: "lacoste slim shirt",
      slug: "lacoste-slim-shirt",
      category: "Shirt",
      image: "/images/p4.png",
      price: 100,
      countInStock: 15,
      brand: "lacoste",
      rating: 3.5,
      numReviews: 9,
      description: "high quality shirt",
    },
  ],
};

export default data;
